apiVersion: v1
kind: Service
metadata:
  name: image-picker-service # 서비스의 이름을 명확히 지정
spec:
  selector:
    app: image-picker-app # Deployment의 라벨과 일치하게 설정
  ports:
    - protocol: TCP
      port: 80        # 외부에서 접근할 포트
      targetPort: 80 # 컨테이너 내부에서 사용할 포트
      nodePort: 30970 # 클러스터 노드에서 접근할 포트
  type: NodePort
